name: Get changed tf config

on:
  # Compare the last commit of main -> to the current commit of a PR branch. 
  # (Note: To compare changes between the last pushed commit to the remote PR branch set `since_last_remote_commit: true`)
  pull_request:
    branches:
      - main

jobs:
  changed-config:
    runs-on: ubuntu-latest
    name: Get changed terraform files
    outputs:
      changed-configs: ${{ steps.changed-files-directory.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Get changed files directory
        id: changed-files-directory
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
          dir_names: "true"
          files: | 
            terraform

      - id: set-matrix
        run: echo "changed_configs={\"container\":${{ steps.changed-files-directory.outputs.all_changed_files }}}" >> $GITHUB_OUTPUT
          
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-directory.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          echo "Then show directory:"
          echo ${{ steps.changed-files-directory.outputs.all_changed_files }}
          echor "Then show json output:"
          echo "changed_configs={\"container\":${{ steps.changed-files-directory.outputs.all_changed_files }}}"
      
  matrix:
    name: Run Terraform deployment job
    runs-on: ubuntu-latest
    needs: [changed-config]
    strategy:
      matrix: ${{ fromJSON(needs.changed-config.outputs.changed-configs) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: ./.github/workflows/terraform.yml
        with:
          config_path: ${{ strategy.matrix }}
