name: Deploy with Terraform

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
defaults:
  run:
    working-directory: ${{ inputs.config-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy with Terraform
    steps:
      - uses: actions/checkout@v3
      
      - name: List all changed files
        run: |
          echo ${{ inputs.config-path }}
          pwd
      