name: Deploy with Terraform

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    name: Get changed terraform files
    outputs:
      changed-config: ${{ steps.changed-files-directory.outputs.all_changed_files }}
    steps:
      - name: List all changed files
        run: |
          
          echo ${{ inputs.config-path }}
      